name: tirmobile
description: Shooting gallery management app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0
  get_it: ^5.0.6
  splash_screen_view: ^3.0.0
  intl: ^0.17.0
  image_picker: ^0.8.2
  dio: ^4.0.0
  flutter_launcher_icons: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_dotenv: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/images/

flutter_icons:
  image_path: 'lib/assets/images/login-page-logo.png'
  android: true
  ios: false